### ISSUE TITLE
New created_at and updated_at fields for all Odahu entities

### ISSUE THREAD

**Issue by mcdoker18** [odahu/odahu-flow#142]
We have to add new fields for all Odahu entites in the status field: 
* created_at - set up this field during creation of an entity. 
* updated_at  - updates this field on every entity update and **creation**.

```yaml
id: ...
spec: ...
status:
  created_at: 2020-02-25T15:28:07+00:00
  updated_at: 2020-02-25T15:28:07+00:00
```

These fields must have string type in the swagger doc.
We can use the [time structure](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/time.go#L33) In the golang codebase.

We should display the new fields in the Odahu UI:
* tables, for example [training table](https://git.epam.com/epmd-legn/odahu-ui/blob/develop/src/views/trainings/TrainingTable.tsx#L16)
* entity view, fro example [training view](https://git.epam.com/epmd-legn/odahu-ui/blob/develop/src/views/trainings/TrainingView.tsx#L56)
